### PR TITLE
fix: sort agent age column numerically

### LINKED ISSUE #15: Make sorting by age numeric rather than alphabetical
Sorting by age looks like it's an alphabetical search. Can you add a numeric sort field for that column so (e.g.) `99 weeks` sorts lower than `100 weeks`? For unknown `?` entries, maybe use -1 as the sort value?

_Originally posted by @fightingmonk in https://github.com/newrelic/nr1-groundskeeper/pull/11#issuecomment-591029359_

### PR DESCRIPTION
**Pull request by danielgolden**
Previously the Agent Age column was sorted alphabetically which bascially meant that sorting by agent age was broken. This PR fixes that issue.

This PR, when merged, will close #15

### CODE REVIEW

File: nerdlets/groundskeeper-nerdlet/index.js [hunk 1]
```diff
@@ -544,9 +544,10 @@ export default class Groundskeeper extends React.Component {
     analysis.outdatedTable = {
       columns: [
         {
-          dataField: 'agentAge',
+          dataField: 'agentAge[1]',
           text: 'Agent age',
           sort: true,
+          formatter: (cell, row) => `${cell} weeks old`,
```
Comment (fightingmonk) [inline nerdlets/groundskeeper-nerdlet/index.js]: Thanks for the sorting fix! My only quibble is that `-1 weeks old` is confusuing when we couldn't find the agent's age. Want to put a ternary in here, something like 
```(cell, row) => (cell >= 0) ? `${cell} weeks old` : 'Unknown'```

Comment (danielgolden) [reply nerdlets/groundskeeper-nerdlet/index.js]: That's a good point. Update coming in a few!
